<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHGEpWut\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHGEpWut/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHGEpWut.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHGEpWut\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHGEpWut\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HGEpWut',
    'container.build_id' => 'a27ff831',
    'container.build_time' => 1574086349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHGEpWut');
