<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0KzAOH6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0KzAOH6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0KzAOH6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0KzAOH6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0KzAOH6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0KzAOH6',
    'container.build_id' => 'a1bb7d20',
    'container.build_time' => 1574412033,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0KzAOH6');
